const CACHE_NAME = 'xiaoleng-site-v6';
const APP_SHELL = [
  '/',
  '/.well-known/keybase.txt',
  '/_config.yml',
  '/1.ttf',
  '/404.html',
  '/articles/1922157354659021001.html',
  '/assets/css/bootstrapxln.min.css',
  '/assets/css/import.css',
  '/assets/css/style2.css',
  '/assets/css/style3.css',
  '/assets/img/articles/GqzO5f_WUAAgS29.jpeg',
  '/assets/img/bilibili/39lk7m9on5.png',
  '/assets/img/bilibili/39lk7z5rj5.png',
  '/assets/img/bilibili/59nm7456wp.jpg',
  '/assets/img/bilibili/59nm7o2v4n.png',
  '/assets/img/bilibili/q0r41o3106.png',
  '/assets/img/bilibili/q0r41o7ylj.png',
  '/assets/img/bilibili/r9v12pklr4.png',
  '/assets/img/bilibili/w45zmx1x8w.png',
  '/assets/img/bilibili/x65z8xpm2z.png',
  '/assets/img/bilibili/y467ozjz0z.png',
  '/assets/img/blog/icon-line.png',
  '/assets/img/blog/icon-twitter.png',
  '/assets/img/common/button-bg.png',
  '/assets/img/common/en-gb.svg',
  '/assets/img/common/favicon.ico',
  '/assets/img/common/icon-192.png',
  '/assets/img/common/icon-512.png',
  '/assets/img/common/icon-bilibili.png',
  '/assets/img/common/icon-close.png',
  '/assets/img/common/icon-facebook.png',
  '/assets/img/common/icon-hamburger.png',
  '/assets/img/common/icon-instagram.png',
  '/assets/img/common/icon-target.png',
  '/assets/img/common/icon-target-white.png',
  '/assets/img/common/icon-telegram.png',
  '/assets/img/common/icon-twitter.png',
  '/assets/img/common/icon-youtube.png',
  '/assets/img/common/ja.svg',
  '/assets/img/common/line.png',
  '/assets/img/common/logo.png',
  '/assets/img/common/zh-cn.svg',
  '/assets/img/email/color-facebook-48.png',
  '/assets/img/email/color-instagram-48.png',
  '/assets/img/email/color-link-48.png',
  '/assets/img/email/color-twitter-48.png',
  '/assets/img/email/color-youtube-48.png',
  '/assets/img/external/icon-bilibili.png',
  '/assets/img/external/icon-facebook.png',
  '/assets/img/external/icon-instagram.png',
  '/assets/img/external/icon-telegram.png',
  '/assets/img/external/icon-twitter.png',
  '/assets/img/external/icon-youtube.png',
  '/assets/img/livecast/og.jpg',
  '/assets/img/odw/1610977807366238213.png',
  '/assets/img/odw/icon-192.png',
  '/assets/img/odw/odwiki-cd-2.jpg',
  '/assets/img/og/og.jpg',
  '/assets/img/qr/xlnmoe.png',
  '/assets/img/shop/liveticket01.jpg',
  '/assets/img/shop/liveticket02.jpg',
  '/assets/img/top/og.jpg',
  '/assets/js/common.js',
  '/assets/js/drawerdrpdwn.js',
  '/assets/js/jquery.mb.YTPlayer.min.js',
  '/assets/js/jquery.min.js',
  '/assets/js/loading/loading.js',
  '/assets/js/markets.js',
  '/assets/js/ofi.min.js',
  '/assets/js/pagetop.js',
  '/assets/js/rellax.min.js',
  '/assets/js/roller-coaster-engine.js',
  '/assets/js/slick.js',
  '/assets/js/slick_single.js',
  '/assets/js/velocity.min.js',
  '/assets/xml/browserconfig.xml',
  '/bitmex.html',
  '/CNAME',
  '/contact.html',
  '/css/colorful.css',
  '/css/images/0.png',
  '/css/images/start.png',
  '/cursor.png',
  '/Drugs/ACL.md',
  '/Drugs/AES.md',
  '/Drugs/ARP.md',
  '/Drugs/ASP.md',
  '/Drugs/ATD.md',
  '/Drugs/BCF.md',
  '/Drugs/BZD.md',
  '/Drugs/CDI.md',
  '/Drugs/CFI.md',
  '/Drugs/Cigarette.md',
  '/Drugs/compound.md',
  '/Drugs/DHCDI.md',
  '/Drugs/DMH.md',
  '/Drugs/DPD.md',
  '/Drugs/DPH.md',
  '/Drugs/DPX.md',
  '/Drugs/DXM.md',
  '/Drugs/EI.md',
  '/Drugs/EtOH.md',
  '/Drugs/GBP.md',
  '/Drugs/KTM.md',
  '/Drugs/MGT.md',
  '/Drugs/MMT.md',
  '/Drugs/MOP.md',
  '/Drugs/NFP.md',
  '/Drugs/Opioids.md',
  '/Drugs/OZP.md',
  '/Drugs/PCT.md',
  '/Drugs/PMZ.md',
  '/Drugs/PPF.md',
  '/Drugs/PR.md',
  '/Drugs/PVR.md',
  '/Drugs/QTP.md',
  '/Drugs/RPD.md',
  '/Drugs/RTL.md',
  '/Drugs/SPM.md',
  '/Drugs/SRIs.md',
  '/Drugs/TAN.md',
  '/Drugs/The_harm_of_dextromethorphan.md',
  '/Drugs/THP.md',
  '/Drugs/TMD.md',
  '/Drugs/TXT.md',
  '/Drugs/VPA.md',
  '/Drugs/ZD.md',
  '/Drugs/ZPC.md',
  '/Drugs/ZPD.md',
  '/Drugs/ZPO.md',
  '/Effects/Antidissociation.html',
  '/Effects/Combination_drugs.html',
  '/Effects/Delirium.html',
  '/Effects/Dissociation.html',
  '/Effects/Introduction_to_Hallucination.html',
  '/fw/absent.html',
  '/fw/authenticatorandroid.html',
  '/fw/authenticatorios.html',
  '/fw/bilibili.html',
  '/fw/bililive.html',
  '/fw/contactform.html',
  '/fw/facebook.html',
  '/fw/instagram.html',
  '/fw/links.html',
  '/fw/qr.html',
  '/fw/shop.html',
  '/fw/stagevideos/01.html',
  '/fw/stagevideos/02.html',
  '/fw/stagevideos/03.html',
  '/fw/stagevideos/04.html',
  '/fw/stagevideos/05.html',
  '/fw/telegram.html',
  '/fw/threads.html',
  '/fw/ticket.html',
  '/fw/x.html',
  '/fw/youtube.html',
  '/images/123.png',
  '/images/articles.png',
  '/images/authenticator.png',
  '/images/bilibili.png',
  '/images/bitmex.png',
  '/images/bitmexxln.png',
  '/images/exe.png',
  '/images/externel.png',
  '/images/folder.png',
  '/images/help.png',
  '/images/img.png',
  '/images/instagram.png',
  '/images/install.png',
  '/images/legal.png',
  '/images/liq.png',
  '/images/logo.png',
  '/images/odw.png',
  '/images/okusuri.png',
  '/images/okusurifolder.png',
  '/images/photos.png',
  '/images/radio.png',
  '/images/restrict.png',
  '/images/stage.png',
  '/images/support.png',
  '/images/telegram.png',
  '/images/text.png',
  '/images/threads.png',
  '/images/url.png',
  '/images/videos.png',
  '/images/x.png',
  '/images/youtube.png',
  '/index.html',
  '/js/3dtext.js',
  '/js/authenticatorandroid.js',
  '/js/authenticatorios.js',
  '/js/bilibili.js',
  '/js/bitmexapp.js',
  '/js/bitmexchinese.js',
  '/js/bitmexsignup.js',
  '/js/colorful.js',
  '/js/facebook.js',
  '/js/instagram.js',
  '/js/install.js',
  '/js/install-llss.js',
  '/js/install-odw.js',
  '/js/marked.min.js',
  '/js/odw.js',
  '/js/telegram.js',
  '/js/telegramgroup.js',
  '/js/telegram-odw.js',
  '/js/threads.js',
  '/js/unya.js',
  '/js/x.js',
  '/js/x-odw.js',
  '/js/youtube.js',
  '/legal/data-handle.html',
  '/livecast.html',
  '/llss/index.html',
  '/manifest.json',
  '/md-view.html',
  '/next_event.html',
  '/passwords/index.html',
  '/passwords/logo.svg',
  '/passwords/logo192.png',
  '/passwords/static/css/2.1c0c6492.chunk.css',
  '/passwords/static/css/main.1c57864a.chunk.css',
  '/passwords/static/js/2.2b73b464.chunk.js',
  '/passwords/static/js/main.fefcc646.chunk.js',
  '/robots.txt',
  '/shop/index.html',
  '/shop/product/39042.html',
  '/shop/product/39043.html',
  '/support/contact.html',
  '/support/pgp.html',
  '/terms.html',
  '/sw.js'
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then((cache) => cache.addAll(APP_SHELL))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(
        keys.filter((key) => key !== CACHE_NAME).map((key) => caches.delete(key))
      ))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return;

  const url = new URL(event.request.url);
  if (url.origin !== self.location.origin) return;

  if (event.request.mode === 'navigate') {
    event.respondWith(
      fetch(event.request)
        .then((response) => response.ok ? response : caches.match('/index.html'))
        .catch(() => caches.match('/index.html'))
    );
    return;
  }

  event.respondWith(
    caches.match(event.request).then((cached) => {
      const network = fetch(event.request).then((response) => {
        if (response && response.ok) {
          const copy = response.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put(event.request, copy));
        }
        return response;
      }).catch(() => cached);

      return cached || network;
    })
  );
});